sources:
- fetcher: url
  name: subs
  options:
    urls:
    - https://fs.v2rayse.com/share/20250322/th62bwskak.yaml
    - http://mm.mibei77.com/202503/03.22Clashikm.yaml
    - ''
    - https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0322.txt
    - https://nodefree.githubrowcontent.com/2025/03/20250322.yaml
    - https://v2rayshare.githubrowcontent.com/2025/03/20250322.yaml
    - https://oneclash.githubrowcontent.com/2025/03/20250322.yaml
    - https://wenode.githubrowcontent.com/2025/03/20250322.yaml
    - https://www.naidounode.com/node/20250322-clash.yaml
    - https://free.datiya.com/uploads/20250322-clash.yaml
  output: sub/sources/dynamicAll.yaml
